version: '3'
services:
  github-runner:
    image: myoung34/github-runner:latest
    environment:
      - REPO_URL=https://github.com/your-username/your-repo
      - RUNNER_NAME=mac-docker-runner
      - RUNNER_TOKEN=your_registration_token
      - RUNNER_WORKDIR=/tmp/github-runner
      - LABELS=mac,docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock