name: "Changelog + PR Validation"

# 📌 This workflow handles both:
# - Enforcing semantic PR titles (so changelogs are meaningful)
# - Automatically generating changelog updates using release-please
#
# 🧠 Purpose:
# We're using this to organize our commit history and changelog structure.
# The goal is to clean up the mess and ensure we have a clear record of changes.
#
# 👀 Note for Andre:
# This will let you (and others) track what’s changing in dev/sbx/prod easily via the generated changelog.

on:
  push:
    branches:
      - development
      - sandbox
      - production
  pull_request:
    types: [opened, edited, reopened]

jobs:
  release-please:
    # 🚀 Only runs on branch push (not PR events)
    name: Update Changelog
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      # 📦 Uses release-please to open a PR that updates CHANGELOG.md based on semantic commits
      - uses: googleapis/release-please-action@v4
        with:
          target-branch: ${{ github.ref_name }}
          release-type: simple
           # No versioning/tags, just changelog updates
        #   skip-github-release: true # Don't create GitHub Releases
        #   target-branch: dev
        #   skip-github-pull-request: true
