name: Checkout Only

on:
  push:
    branches:
      - main  # or your desired branch
  pull_request:

jobs:
  checkout:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4